version: '3.4'

services:
  presentation:
    image: ${DOCKER_REGISTRY-}presentation
    build:
      context: .
      dockerfile: Presentation/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - mssql     
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my-network

  rabbitmq:
    image: rabbitmq:management
    container_name: my-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: my-mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - ./data:/var/opt/mssql/data
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
